sudo: false
language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
branches:
    - umccr
jdk:
  - openjdk8
  - openjdk11
install:
- ./gradlew clean
- ./gradlew assemble
script:
- ./gradlew -b build.gradle build
